# Generated by Django 5.1.5 on 2025-02-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_registeruser_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateLeadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('uniqueId', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=122)),
                ('Source', models.CharField(max_length=122)),
                ('Assigned', models.CharField(max_length=255)),
                ('lcd', models.CharField(max_length=255)),
                ('doc', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('addnOTE', models.CharField(max_length=500)),
            ],
        ),
    ]
